package chat

const (
	EventSessionReady        = "session.ready"
	EventMessageSend         = "message.send"
	EventMessageAck          = "message.ack"
	EventMessageNew          = "message.new"
	EventMessageError        = "message.error"
	EventMessageDelivered    = "message.delivered"
	EventMessageRead         = "message.read"
	EventMessageEdit         = "message.edit"
	EventMessageDelete       = "message.delete"
	EventMessageUpdated      = "message.updated"
	EventMessageDeleted      = "message.deleted"
	EventMutationAck         = "message.mutation.ack"
	EventMutationError       = "message.mutation.error"
	EventTypingStart         = "typing.start"
	EventTypingStop          = "typing.stop"
	EventPresenceChanged     = "presence.changed"
	EventConversationUpdated = "conversation.updated"
	EventCallInvite          = "call.invite"
	EventCallRinging         = "call.ringing"
	EventCallAccept          = "call.accept"
	EventCallReject          = "call.reject"
	EventCallOffer           = "call.offer"
	EventCallAnswer          = "call.answer"
	EventCallICE             = "call.ice"
	EventCallHangup          = "call.hangup"
	EventCallBusy            = "call.busy"
	EventCallError           = "call.error"
)
